const assert=require('assert');
const C=require('../core.js');
const now=Date.now();
let db=C.createInitialDb(undefined,now);
assert.equal(db.version,3);
let cand=C.selectNext(db,now);assert(cand&&cand.item&&cand.track);
let p=C.buildProbe(db,cand.item,'recall',now);assert.equal(p.kind,'construct');
let g=C.gradeProbe({...p,kind:'text'},cand.item.target);assert.equal(g.verdict,'pass');
let st=C.blankItemState(now);let before=JSON.stringify(st.tracks.recall);let u=C.updateMemoryState(st.tracks.recall,{verdict:'uncertain',hintLevel:0,latencyMs:1000},now,.9);assert.equal(u.skipped,true);assert.equal(JSON.stringify(u.after),before);
let item=db.items.find(x=>x.id==='listen-to-music');let probe=C.buildProbe(db,item,'recall',now);let r=C.processReview(db,{probe:{...probe,kind:'text'},answer:'listen music',hintLevel:0,attemptCount:1,startedAt:now-2000},now);assert(r.grading.errorTags.includes('missing_preposition'));
let useProbe={...C.buildProbe(db,item,'use',now),kind:'use-text',requireTargetInSentence:true};let rr=C.processReview(db,{probe:useProbe,answer:'I listen to music every evening.',hintLevel:0,attemptCount:1,startedAt:now-1000},now+1);assert.equal(rr.grading.verdict,'pass');assert(db.states[item.id].evidence.recall>0);
let s=db.states[item.id];s.evidence.comprehension=.9;s.evidence.use=.7;assert.equal(C.isTrackRetired(s,'comprehension'),true);
console.log('7 core checks passed');
