const assert=require('assert');
const fs=require('fs');
const path=require('path');
const WLK=require('../word-lookup.js');
const CAT=require('../starter-catalog.js');

let checks=0;
function ok(){checks++;}

// youtubeVideoId — every URL shape learners realistically paste.
{
  const cases=[
    ['https://www.youtube.com/watch?v=abc123XYZ_-','abc123XYZ_-'],
    ['https://youtu.be/abc123XYZ_-','abc123XYZ_-'],
    ['https://www.youtube.com/shorts/abc123XYZ_-','abc123XYZ_-'],
    ['https://www.youtube.com/embed/abc123XYZ_-','abc123XYZ_-'],
    ['https://www.youtube.com/watch?v=abc123XYZ_-&t=42s','abc123XYZ_-'],
    ['https://example.com/not-youtube',null],
    ['',null],
    [null,null],
  ];
  for(const [url,expected]of cases)assert.strictEqual(WLK.youtubeVideoId(url),expected,url);
  ok();
}

// lookup() — mocked fetch + in-memory localStorage stand-in.
{
  const store=new Map();
  global.localStorage={getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)};
  const calls=[];
  global.fetch=async(url)=>{
    calls.push(url);
    if(url.includes('dictionaryapi.dev')){
      return {ok:true,text:async()=>JSON.stringify([{meanings:[{partOfSpeech:'verb',definitions:[{definition:'to move quickly using legs'}]},{partOfSpeech:'noun',definitions:[{definition:'an act of running'}]}]}])};
    }
    if(url.includes('mymemory')){
      return {ok:true,text:async()=>JSON.stringify({responseData:{translatedText:'đang chạy'},matches:[{translation:'đang chạy'},{translation:'chạy bộ'},{translation:'QUẢNG CÁO SPAM'}]})};
    }
    throw new Error('unexpected url '+url);
  };

  (async()=>{
    const r=await WLK.lookup('Running');
    assert.strictEqual(r.word,'running');
    assert.strictEqual(r.en.length,2);
    assert.strictEqual(r.en[0].pos,'verb');
    assert.strictEqual(r.vi.main,'đang chạy');
    // Alternative glosses dedupe against main + drop all-caps spam.
    assert.deepStrictEqual(r.vi.alternatives,['chạy bộ']);
    assert(!r.cached);
    ok();

    // Second lookup hits cache — no network.
    const before=calls.length;
    const r2=await WLK.lookup('running');
    assert.strictEqual(r2.cached,true);
    assert.strictEqual(calls.length,before,'cache hit must not refetch');
    ok();

    // Offline path returns cached data or empty shape — never throws.
    const r3=await WLK.lookup('unknown',{online:false});
    assert.strictEqual(r3.offline,true);
    assert.deepStrictEqual(r3.en,[]);
    ok();

    // API failure (non-ok) → lookup still resolves with empty results.
    global.fetch=async()=>({ok:false,status:500,text:async()=>'server error'});
    store.clear();
    const r4=await WLK.lookup('broken');
    assert.deepStrictEqual(r4.en,[]);
    assert.strictEqual(r4.vi,null);
    ok();
    console.log(`word-lookup: ${checks} checks passed`);
    runSyncChecks();
  })().catch(err=>{console.error(err);process.exit(1);});
}

// ── parseYouTubeTranscript — real youtube-transcript.ai markdown shape ──
function runSyncChecks(){
  const md=`# Transcript: A Test Video

Source video: https://www.youtube.com/watch?v=abc123XYZ_-
Language: en · Duration: 1:10 · Words: 30

## Transcript
[0:00] First sentence here. Second one follows. [♪♪♪]

[0:30] Third line arrives now. And a fourth line too.

---
Generated by https://youtube-transcript.ai`;
  {
    const {title,segments}=WLK.parseYouTubeTranscript(md);
    assert.strictEqual(title,'A Test Video');
    // 4 sentences → 4 segments; paragraph 1 sentences share the 30s gap.
    assert.strictEqual(segments.length,4);
    assert.strictEqual(segments[0].text,'First sentence here.');
    assert.strictEqual(segments[0].start,0);
    assert(segments[2].start===30,'sentence in second paragraph starts at its mark');
    assert(segments[0].end>0&&segments[0].end<30,'interpolated end within paragraph window');
    assert(!segments.some(s=>s.text.includes('♪')),'music markers stripped');
    ok();
  }
  {
    // Garbage in → empty, never throws.
    const {title,segments}=WLK.parseYouTubeTranscript('not a transcript at all');
    assert.strictEqual(title,'');
    assert.deepStrictEqual(segments,[]);
    ok();
  }
  {
    // Catalog integrity: every bundled item imports cleanly — real sentences,
    // VN translations present, unique ids, valid CEFR tag.
    const seen=new Set();
    const levels=new Set(['A1','A2','B1','B2','C1','C2']);
    for(const item of CAT.ITEMS){
      assert(item.id&&!seen.has(item.id),'unique catalog id: '+item.id);
      seen.add(item.id);
      assert(levels.has(item.level),'valid level: '+item.id);
      assert(item.lines.length>=6,'enough lines: '+item.id);
      for(const [en,vn]of item.lines){
        assert(en&&/[a-zA-Z]/.test(en),'English line non-empty in '+item.id);
        assert(vn&&/[àáảãạăằắẳẵặâầấẩẫậèéẻẽẹêềếểễệìíỉĩịòóỏõọôồốổỗộơờớởỡợùúủũụưừứửữựỳýỷỹỵđ]/i.test(vn),'VN translation present in '+item.id);
      }
    }
    ok();
  }
  console.log(`word-lookup+catalog: ${checks} checks total passed`);
}
